
# mysql set
spring:
  application:
    name : pj

  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://43.200.120.76:3306/pj?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username : admin
    password : yj0113

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        ddl-auto: none

